__title__ = 'time2relax'  # noqa: D100
__description__ = 'A CouchDB driver for Python.'
__url__ = 'https://github.com/rwanyoike/time2relax'
__version__ = '0.5.2'
__author__ = 'Raymond Wanyoike'
__author_email__ = 'raymond.wanyoike@gmail.com'
__license__ = 'MIT'
__copyright__ = '2017 Raymond Wanyoike'
__couch__ = u'\u2728 \U0001f6cb \u2728'
